# Generated by Django 3.1.2 on 2020-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ab', models.IntegerField()),
                ('avg', models.DecimalField(decimal_places=3, max_digits=4)),
                ('babip', models.DecimalField(decimal_places=3, max_digits=4)),
                ('h', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('obp', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ops', models.DecimalField(decimal_places=3, max_digits=4)),
                ('r', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('slg', models.DecimalField(decimal_places=3, max_digits=4)),
                ('so', models.IntegerField()),
                ('vorp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('warp', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pitchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dra', models.DecimalField(decimal_places=2, max_digits=4)),
                ('era', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hr9', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ip', models.DecimalField(decimal_places=1, max_digits=4)),
                ('so', models.IntegerField()),
                ('so9', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sv', models.IntegerField()),
                ('vorp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('warp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('whip', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
