# Generated by Django 3.1.2 on 2020-11-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_homeruns_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hr162',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hr2020',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
