# Generated by Django 3.1.2 on 2020-11-09 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201109_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeruns',
            name='name',
        ),
        migrations.AddField(
            model_name='homeruns',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.player'),
            preserve_default=False,
        ),
    ]
